import numpy as np 
print("1D Array")
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print("2D Array")
arr=np.array([[1,2,3],[4,5,7],[7,8,9]])
print(arr)
print("2D Array Shape ",arr.shape)
print("Array of 0,1 is",arr[0,1])
print("3D Array")
arr=np.array()
print(arr)
